# -*- coding: utf-8 -*-
"""thuchanhEVI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kjOjQaWBNVvqCq3pUb9_2N5zsXuohMZ5
"""

!pip -q install --upgrade xee geemap hvplot

import ee
ee.Authenticate()
ee.Initialize(project='vothanhhuy', opt_url="https://earthengine-highvolume.googleapis.com") # Replace 'YOUR_PROJECT_ID' with your actual Google Cloud Project ID

import geemap
m = geemap.Map()
m

if m.draw_last_feature:
    roi = m.draw_last_feature.geometry()
    print('Đã lấy được hình học của đối tượng bạn đã vẽ:')
    print(roi)
else:
    print('Bạn chưa vẽ bất kỳ đối tượng nào trên bản đồ. Vui lòng vẽ một đối tượng trên bản đồ Geemap trước khi chạy ô này.')

roi = m.draw_last_feature.geometry()
roi

viirs = (
    ee.ImageCollection("NASA/VIIRS/002/VNP13A1")
    .filterDate('2020-01-01', '2021-01-01')
    .select('EVI')
)
viirs.size().getInfo()

import xarray as xr

ds = xr.open_dataset(
    viirs,
    engine='ee',
    crs='EPSG:4326',
    geometry=roi,
    scale=0.1  # theo code mẫu bạn đưa
)

ds = ds.sortby('time') * 1
ds

ds_mean = ds.mean(dim='time')
ds_mean

import hvplot.xarray  # quan trọng

ds_mean.EVI.hvplot(
    x='lon', y='lat',
    height=500,
    cmap='RdYlGn',
    robust=True,
    title='Average EVI - 2020'
)

ds_mean.EVI.hvplot.quadmesh(
    x='lon', y='lat',
    height=500,
    cmap='RdYlGn',
    robust=True
)

ds_mean.EVI.hvplot.contour(
    x='lon', y='lat',
    height=500,
    cmap='RdYlGn',
    robust=True,
    levels=10
)

ds_mean.EVI.hvplot.contour(
    x='lon', y='lat',
    height=500,
    cmap='RdYlGn',
    robust=True,
    levels=20
)

ds_mean.EVI.hvplot.contourf(
    x='lon', y='lat',
    height=500,
    cmap='RdYlGn',
    robust=True,
    levels=20
)

ds_mean.EVI.hvplot.contourf(
    x='lon', y='lat',
    height=500,
    cmap='RdYlGn',
    robust=True,
    levels=40
)

ds.EVI.hvplot(
    x='lon', y='lat',
    height=500,
    cmap='RdYlGn',
    robust=True,
    groupby='time',
    widget_location='bottom',
    widget_type='scrubber'
)

ds.EVI.hvplot(
    x='lon', y='lat',
    height=500,
    cmap='RdYlGn',
    robust=True,
    groupby='time',
    widget_location='bottom',
    widget_type='scrubber' # Đã sửa từ 'select' thành 'scrubber'
)

viirs2 = (
    ee.ImageCollection("NASA/VIIRS/002/VNP13A1")
    .filterDate('2020-01-01', '2021-01-01')
    .select('NDVI')  # nếu có
)